all: usodiccionario usoguia

usoguia: ./src/usoguia.cpp
	g++ -g -o ./bin/usoguia ./src/usoguia.cpp -I ./include/

usodiccionario: ./src/usodiccionario.cpp
	g++ -g -o ./bin/usodiccionario ./src/usodiccionario.cpp -I ./include/
