.TH "imagen.h" 3 "Sábado, 7 de Noviembre de 2020" "ClaseImagen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
imagen.h \- Fichero cabecera del TDA \fBImagen\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'imagenES\&.h'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBImagen\fP"
.br
.RI "T\&.D\&.A\&. Racional\&. "
.in -1c
.SS "typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned char \fBbyte\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Fichero cabecera del TDA \fBImagen\fP\&. 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para ClaseImagen del código fuente\&.
