.TH "repImagen" 3 "Sábado, 7 de Noviembre de 2020" "ClaseImagen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
repImagen \- Rep del TDA \fBImagen\fP 

.SH "Invariante de la representación"
.PP
El invariante es \fIrep\&.filas>=0\fP & rep\&.cols>=0
.SH "Función de abstracción"
.PP
Un objeto válido \fIrep\fP del TDA \fBImagen\fP representa al valor viene representado por un valor positivo de filas y columnas, así como un valor comprendido 0 <= datos(i,j) <= 255 para cada i,j (filas, columnas) del array bidimensional 
